version: '3.1'

services: 
  redis:
    image: redis:6.2
    restart: always
    networks:
      - network_bridge
    volumes:
      - $PWD/redis_data:/data
    ports:
      - 6379:6379

networks:
  network_bridge:
    driver: bridge