version: '3.1'

services:

  db:
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_PASSWORD: toor
    volumes: 
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4-standalone
    restart: always
    ports:
      - 8080:8080

volumes: 
  pg_data: