version: "3.7"

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    networks:
      - network_bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - $PWD/caddy_data:/data
      - $PWD/caddy_config:/config

networks:
  network_bridge:
    driver: bridge