# docker run -d --restart always -v /var/run/docker.sock:/var/run/docker.sock -v <data dir>:/opt/onedev -p 6610:6610 -p 6611:6611 1dev/server
# https://code.onedev.io/projects/onedev-manual/blob/main/pages/run-as-docker-container.md

version: '3.1'

services: 
  onedev:
    image: 1dev/server
    restart: always
    networks:
      - network_bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/onedev_data:/opt/onedev
    ports:
      - "6610:6610"
      - "6611:6611"

networks:
  network_bridge:
    driver: bridge