version: '3'

services:
 
  netdata:
    image: netdata/netdata
    ports:
      - 19999:19999
    restart: unless-stopped
    networks:
      - network_bridge
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - $PWD/netdataconfig:/etc/netdata
      - $PWD/netdatalib:/var/lib/netdata
      - $PWD/netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro

networks:
  network_bridge:
    driver: bridge