version: '2'

volumes:
  app_data:
  db_data:

services:
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_read_only_compressed=OFF
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=toor
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app:
    image: nextcloud:20.0
    restart: always
    ports:
      - 8080:80
    volumes:
      - app_data:/var/www/html
    environment:
      - MYSQL_PASSWORD=toor
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db